name: test workflow
run-name: ${{ github.actor }} - ${{ github.sha }}


on:
  workflow_dispatch:
  push:
    branches: [ "main" , "develop"]
  pull_request:
    branches: [ "main" ]

env:
  PYTHON_VERSION: 3.11

jobs:

  python-ci:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src


    steps:
      - uses: actions/checkout@v4
        name: Checkout repository

      - uses: actions/setup-python@v5
        name: Setup Python ${{ env.PYTHON_VERSION }}
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 coverage
          pip install -r requirements.txt

      - name: Test app and generate coverage
        run: |	
          coverage run manage.py test
          coverage report

      - name: Lint with flake8
        run: |
          flake8 . --exit-zero --show-source --statistics

      - name: Check Complexity
        run: |
          cd ../
          flake8 . --exit-zero --max-complexity=10 --statistics

      - uses: actions/upload-artifact@v2
        name: Upload Python code as an artifact
        with:
          name: python-code
          path: .
